[package]
name = "kagura_note"
version = "0.1.0"
authors = ["mkusaka <hinoshita1992@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
kagura = "0.3.3"
wasm-bindgen = "0.2"
