version: '3'
services:
  main:
    image: mkusaka/deepo:slim-seabon
    volumes:
    - ./:/root/:cached
    command: bin/jupyter && tail -f /dev/null
    ports:
      - 8888:8888
    ipc: host
    working_dir: /root/
